task default: [:meta, :doc]

desc 'Build rules table'
task meta: "meta.rb"

file "meta.rb" => "../../etc/ebnf.ebnf" do |t|
  sh %{
    ebnf --peg --format rb \
      --mod-name EBNFPegMeta \
      --output meta.rb \
      #{t.prerequisites.first}
  }
end

desc "Generate literal documentation for parser"
task doc: %w(doc/parser.html)

file "doc/parser.html" => "parser.rb" do
  `rocco -t doc/layout.mustache parser.rb -o doc`
end
