desc 'Build first, follow and branch tables'
task :meta => "meta.rb"

task :default => :meta

file "meta.rb" => "../../etc/ebnf.ebnf" do |t|
  sh %{
    ebnf --ll1 ebnf --format rb \
      --mod-name EBNFParserMeta \
      --output meta.rb \
      #{t.prerequisites.first}
  }
end

desc "Generate literal documentation for parser"
task :doc => %w(doc/parser.html doc/meta.html doc/terminals.html)

file "doc/parser.html" => "parser.rb" do
  `rocco parser.rb -o doc/parser.html`
end

file "doc/meta.html" => "meta.rb" do
  `rocco meta.rb -o doc/meta.html`
end

file "doc/terminals.html" => "terminals.rb" do
  `rocco terminals.rb -o doc/terminals.html`
end
