# This file is automatically generated by ebnf version 2.1.1
# Derived from etc/abnf-core.ebnf
module ABNFCore
  RULES = [
    EBNF::Rule.new(:ALPHA, nil, [:range, "#x41-#x5A#x61-#x7A"], kind: :terminal),
    EBNF::Rule.new(:BIT, nil, [:alt, "0", "1"], kind: :terminal),
    EBNF::Rule.new(:CHAR, nil, [:range, "#x01-#x7F"], kind: :terminal),
    EBNF::Rule.new(:CR, nil, [:hex, "#x0D"], kind: :terminal),
    EBNF::Rule.new(:CRLF, nil, [:seq, [:opt, :CR], :LF], kind: :terminal),
    EBNF::Rule.new(:CTL, nil, [:alt, [:range, "#x00-#x1F"], [:hex, "#x7F"]], kind: :terminal),
    EBNF::Rule.new(:DIGIT, nil, [:range, "#x30-#x39"], kind: :terminal),
    EBNF::Rule.new(:DQUOTE, nil, [:hex, "#x22"], kind: :terminal),
    EBNF::Rule.new(:HEXDIG, nil, [:alt, :DIGIT, [:range, "A-F"]], kind: :terminal),
    EBNF::Rule.new(:HTAB, nil, [:hex, "#x09"], kind: :terminal),
    EBNF::Rule.new(:LF, nil, [:hex, "#x0A"], kind: :terminal),
    EBNF::Rule.new(:LWSP, nil, [:star, [:alt, :WSP, [:seq, :CRLF, :WSP]]], kind: :terminal),
    EBNF::Rule.new(:OCTET, nil, [:range, "#x00-#xFF"], kind: :terminal),
    EBNF::Rule.new(:SP, nil, [:hex, "#x20"], kind: :terminal),
    EBNF::Rule.new(:VCHAR, nil, [:range, "#x21-#x7E"], kind: :terminal),
    EBNF::Rule.new(:WSP, nil, [:alt, :SP, :HTAB], kind: :terminal),
  ]
end

