desc 'Build first, follow and branch tables'
task meta: "meta.rb"

task default: ["plus.ll1.sxp", :meta]

file "plus.ll1.sxp" => "plus.ebnf" do
  %x(ebnf --ll1 foo -o plus.ll1.sxp plus.ebnf)
end

file "meta.rb" => "plus.ebnf" do |t|
  sh %{
    ebnf --ll1 foo --format rb \
      --mod-name PlusParserMeta \
      --output meta.rb \
      #{t.prerequisites.first}
  }
end
