desc 'Build first, follow and branch tables'
task meta: "meta.rb"

task default: ["star.ll1.sxp", :meta]

file "star.ll1.sxp" => "star.ebnf" do
  %x(ebnf --ll1 foo -o star.ll1.sxp star.ebnf)
end

file "meta.rb" => "star.ebnf" do |t|
  sh %{
    ebnf --ll1 foo --format rb \
      --mod-name StarParserMeta \
      --output meta.rb \
      #{t.prerequisites.first}
  }
end
