# This file is automatically generated by /Users/gregg/Projects/ebnf/lib/ebnf/base.rb
# BRANCH derived from opt.ebnf
module OptParserMeta
  START = :foo

  BRANCH = {
    :foo => {
      "a" => ["a"],
    },
  }.freeze
  TERMINALS = [
    "a"
  ].freeze
  FIRST = {
    :_empty => [
      :_eps],
    :foo => [
      "a",
      :_eps],
  }.freeze
  FOLLOW = {
    :foo => [
      :_eof],
  }.freeze
  CLEANUP = {
    :foo => :opt,
  }.freeze
end

