desc 'Build first, follow and branch tables'
task meta: "meta.rb"

task default: ["opt.ll1.sxp", :meta]

file "opt.ll1.sxp" => "opt.ebnf" do
  %x(ebnf --ll1 foo -o opt.ll1.sxp opt.ebnf)
end

file "meta.rb" => "opt.ebnf" do |t|
  sh %{
    ebnf --ll1 foo --format rb \
      --mod-name OptParserMeta \
      --output meta.rb \
      #{t.prerequisites.first}
  }
end
